### ISSUE TITLE
Installation steps lead to `module 'typing_extensions' has no attribute '_tp_cache'`

### ISSUE THREAD

**Issue by A-Telfer** [DeepLabCut/napari-DLCLabelingAlpha#10]
Just reporting an error message following the current installation instructions

## Problem
After installing the dlclabel environment from the environment.yml file 
```
git clone --single-branch https://github.com/DeepLabCut/DeepLabCut-label.git
cd DeepLabCut-label
conda env create -f environment.yml
conda activate dlclabel
```
I then try to launch dlclabel

```python
ipython
import dlclabel
dlclabel.show()
```
And I get this error
```
AttributeError: module 'typing_extensions' has no attribute '_tp_cache'
```

## Solution
This seems to be because of an old issue with Napari https://github.com/napari/napari/issues/1954

This project seems to install an older version of Napari (eg. `napari==0.4.0` in requirements.txt). 

Upgrading Napari to the current version (0.4.12)  using `pip install -U napari` appears to fix the issue.

**Comment by jeylau** [comment]
Hey @A-Telfer, thanks for reporting the error. The issue you reference indicates that it occurs python 3.9, although python3.8 should be installed with the environment.yaml we provide; which one do you have?
Also note that we had pinned napari to an old version because they had introduced pydantic models in the meantime (and many more changes), which partly broke subclassing their Layers. I have just tested it with napari 0.4.12, and it does cause the GUI to crash on my laptop 😨 Is the GUI functional (past opening) on your side?

**Comment by A-Telfer** [comment]
The python version for the environment is 3.8.12, it would be unfortunate if the patch version matters

Perhaps there's some other system difference? I'm on Ubuntu 21.04. It seems like someone else might have had this issue too

The GUI works on my laptop (loads images at least), not totally sure what to do with it yet to test it more. I have to read up on napari some more. Looks great though!

**Comment by backyardbiomech** [comment]
It was a problem with the typing_extensions module, which was updated to 4.0 recently. Downgrading in the env with

```
python -m pip install typing_extensions==3.10.0.2
```

fixes the error.

Also mentioned in the [forum](https://forum.image.sc/t/key-error-when-checking-frames-labelled-in-napari-gui/60089/10).
